### ISSUE TITLE
Error in Partial least square regression analysis  for only  cortical regions included 

### ISSUE THREAD

**Issue by lenachenpumc** [alegiac95/Imaging-transcriptomics#22]
Dear alegiac95, 
![123](https://github.com/alegiac95/Imaging-transcriptomics/assets/111960642/70c80529-f188-4d5d-918e-060f447b8838)

Thank you for your toolbox "Imaging-transcriptomics".
I have met bug performing this code
`(transcriptomics) PS C:\Users\lena> imagingtranscriptomics --input F:/banana/Reslice_7_1.nii --regions cort --no-gsea pls --ncomp 1`

The error is 
`Traceback (most recent call last):
  File "D:\anaconda\envs\transcriptomics\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\anaconda\envs\transcriptomics\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\anaconda\envs\transcriptomics\Scripts\imagingtranscriptomics.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "D:\anaconda\envs\transcriptomics\lib\site-packages\imaging_transcriptomics\script\imagingtranscriptomics.py", line 103, in main
    transcriptomics.run(outdir,
  File "D:\anaconda\envs\transcriptomics\lib\site-packages\imaging_transcriptomics\transcriptomics.py", line 320, in run
    self.scan_data[0:34, :]
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed`

Please, how to solve this error? Thank you!

**Comment by alegiac95** [comment]
Hi, this issues seems to be related somehow in a small bug, which should now be corrected. try to upgrade the toolbox and see if the error keeps popping up
